INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('<none>', '<none>', 0);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Peanut Butter 80 oz', 'ounce', 80);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Peanut Butter 40 oz', 'ounce', 40);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Creamy Peanut Butter 40 oz', 'ounce', 40);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Peanut Butter Powder', 'ounce', 30);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Peanut Butter to go', 'ounce', 12);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Peanut Butter Creamy', 'ounce', 64);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Creamy Peanut Butter 16 oz', 'ounce', 16);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Peanut Butter 16 oz', 'ounce', 16);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Peanut Butter Super Chunk', 'ounce', 15);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Honey Roasted Peanuts', 'ounce', 12);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Butter Unsalted', 'ounce', 12);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('BUTTER SALTED SWEET CREAM 16 OZ', 'ounce', 32);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Pure Irish Grass-fed Butter, 8 Oz (10 Pack)', 'ounce', 80);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Canned Butter', 'ounce', 12);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Dry Roasted Peanuts with Pure Sea Salt, 34.5 Ounce', 'ounce', 34);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('In-Shell Classic Roast Peanuts Salted 5 Pounds', 'pounds', 5);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Raw Redskin Peanuts (Unsalted) 5LB Bag Bulk', 'pounds', 5);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Signature Super XL VA Peanuts, 40 Ounce', 'ounce', 40);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('washing machine detergent', 'pounds', 2);
INSERT INTO PriceCheckData.item (itemName, unit, unitValue) VALUES ('Ketchup', 'ounce', 24);