INSERT INTO PriceCheckData.brand (brandName) VALUES ('Blue Diamond Growers');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Breakstone''s');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Cabot');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Challenge');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Crystal Farms');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Darigold');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Deans');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Emerald');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Fisher');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Hunt''s');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Imperial');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Keller''s');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Kerrygold');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Kirkland');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Land O'' Lakes');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('MaraNatha');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Planters');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Skippy');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Smucker''s');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Tide');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Tillamook');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Trader Joe''s');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Unknown');
INSERT INTO PriceCheckData.brand (brandName) VALUES ('Wonderful');